module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'users',
    CATEGORY_COLLECTION:"categories",
    CART_COLLECTION:"cart",
    ORDER_COLLECTION:'orders',
    ADDRESS_COLLECTION:'address',
    BANNER_COLLECTION:'banners',
    COUPON_COLLECTION:'coupons',
    WISHLIST_COLLECTION:'wishlist'
}